main/urls.py
from django.urls import path
from main.views import main_page,RestApiLight,rest_api_light,UserLoginView


app_name='main'
urlpatterns=[
    path('api/',RestApiLight.as_view(),name='rest_page'),
    path('',main_page,name='main_page'),
    path('api1/',rest_api_light,name='rest_page1'),
    path('login/',UserLoginView.as_view(),name='login_page'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render,HttpResponse
import json,os

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated


if os.environ.get('GPIO_EXIST'):
    import RPi.GPIO as GP
    pin = int(os.environ.get('LIGHT_PIN'))
    GP.setmode(GP.BCM)
    GP.setup(pin,GP.OUT)
else:
    import repl_gp as GP
    pin='None'

@login_required(login_url='/login/')
def main_page(request):
    with open('data.json','r') as f:
        old_data=json.load(f)
    context={'old_data':old_data}
    if request.method=='POST':
        print(request.POST)
        unf_data=dict(request.POST)
        print(unf_data)
        if unf_data['hour']!=None and unf_data['minute']!=None:
            data={'hour':int(unf_data['hour'][0]),'minute':int(unf_data['minute'][0])}
            if unf_data.get('condition'):
                data['condition']=1
            else:
                data['condition']=0
            context.update({'data': data})
            with open('data.json','w') as f:
                json.dump(data,f,indent=4)
    return render(request,'main.html',context)


class RestApiLight(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        # print(request.data)
        GP.output(pin,request.data['state'])
        return Response('hello')

@api_view(http_method_names=['POST'])
def rest_api_light(request):
    if request.method=="POST":
        print(request.data)
    return Response('hello')


class UserLoginView(LoginView):
    template_name = 'login.html'
    next_page = '/'

main/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button>OK</button>
</form>
</body>
</html>

main/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="background: #aeec94;">
<div class=base_form>
<div class=base_form_cell>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        <tr><td><label for="hour_input">Час </label></td><td><input type="text" id="hour_input" name="hour"></td></tr>
        <tr><td><label for="min_input">Минута </label></td><td><input type="text" id="min_input" name="minute"></td></tr>
        <tr><td><label for="cond_input">Состояние </label></td><td><input type="checkbox" id="cond_input" name="condition"></td></tr>
        <tr><td><button>Ok</button></td></tr>
    </table>
</form>
</div>
<div class=base_form_cell>
    <div class=base_form_cell_inner>
        <input class="big_button" type="button" id="on_button" value="ON">
        <input class="big_button" type="button" id="off_button" value="OFF">
        <a href=""><button class="big_button">RELOAD</button></a>
    </div>
</div>
</div>
<div class=data_show>
    <div class=data_show_cell>
    <table>
    <tr><td><span>Тип:</span></td><td><span>Текущий</span></td></tr>
    {% for i, key in data.items %}
        <tr><td>{{i}}</td><td>{{key}}</td></tr>
    {% endfor %}
    </table>
    </div>
    <div class=data_show_cell>
    <table>
    <tr><td><span>Тип:</span></td><td><span>Задано</span></td></tr>
    {% for i, key in old_data.items %}
        <tr><td>{{i}}</td><td>{{key}}</td></tr>
    {% endfor %}
    </table>
    </div>
</div>
<script>
    let cookies=document.cookie
    let token=cookies.slice(cookies.indexOf('csrftoken')+10)
    let on_button=document.getElementById('on_button')
    let off_button=document.getElementById('off_button')
    on_button.addEventListener('click',fn1)
    off_button.addEventListener('click',fn1)
    function fn1(st) {
        let input_id=st['path'][0]['id']
        let ans='error'
        console.log(input_id)
        if (input_id==='on_button') {
            ans = 1
        }
        if (input_id==='off_button') {
            ans = 0
        }
        fetch('{% url "main:rest_page" %}',{
            method:'POST',
            headers:{"Content-Type":"application/json","X-CSRFToken":token},
            body:JSON.stringify({'state':ans})
        })
    }
</script>
</body>
</html>